# Site
name: 'Optinest Digital'
description: 'Boutique digital agency specializing in high-performance websites and smart SEO strategies..'
logo: 'assets/images/logo.png'
favicon: 'assets/images/ico.png'
baseurl: ''
url: 'https://optinestdigital.com'
email: 'optinestdigital@gmail.com'
 
include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    admin:
      name:           Optinest
      site:           https://optinestdigital.com
      avatar:         assets/images/logo.png
      bio:            "We're a boutique digital agency that specializes in creating high-performance websites and implementing smart SEO strategies to help businesses thrive in the digital landscape."
      email:          optinestdigital@gmail.com
      facebook:        https://facebook.com/optinestdigital
      twitter:        https://x.com/optinestdigital

    
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: admin
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 9
paginate_path: "/blog/page:num/"

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
 