# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/images/blog"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
     
      - {
          label: "Tag",
          name: "tags",
          widget: "select",
          options: ["featured", "sticky"],
        }
      
      - {
          label: "TOC",
          name: "toc",
          widget: "select",
          options: ["true", "false"],
        }
     
      - { label: "Featured", name: "image", widget: "image" }
      - { label: "Category", name: "categories", widget: "list" }
      - {
          label: "Author",
          name: "author",
          widget: "select",
          options: ["admin", "Godsmurf"],
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", required: false }
      - { label: "SEO Title", name: "seo_title", widget: "string", required: false }
      - { label: "SEO Description", name: "seo_description", widget: "text", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Settings"
    files:
      - file: "_config.yml"
        label: "Site Settings"
        name: "site"
        fields:
          - { label: "Site Name", name: "name", widget: "string" }
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Site Logo", name: "logo", widget: "image" }
          - { label: "Favicon", name: "favicon", widget: "image" }
          - { label: "Base URL", name: "baseurl", widget: "string" }
          - { label: "Site URL", name: "url", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Posts Per Page", name: "paginate", widget: "number" }
          - { label: "Permalink Structure", name: "permalink", widget: "string" }
          - { label: "Markdown Processor", name: "markdown", widget: "select", options: ["kramdown", "redcarpet"] }
          - { label: "Syntax Highlighter", name: "highlighter", widget: "select", options: ["rouge", "pygments"] }

      - file: "_data/authors.yml"
        label: "Authors"
        name: "authors"
        fields:
          - label: "Admin"
            name: "admin"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Website", name: "site", widget: "string" }
              - { label: "Avatar", name: "avatar", widget: "image" }
              - { label: "Bio", name: "bio", widget: "text" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Facebook", name: "facebook", widget: "string" }
              - { label: "Twitter", name: "twitter", widget: "string" }

      - file: "_data/navigation.yml"
        label: "Navigation"
        name: "navigation"
        fields:
          - { label: "Main Menu", name: "main", widget: "list", fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "New Tab", name: "new_tab", widget: "boolean", required: false }
            }
          - { label: "Footer Menu", name: "footer", widget: "list", fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "New Tab", name: "new_tab", widget: "boolean", required: false }
            }